### ISSUE TITLE
Unable to update from 2.0.0 to 2.1.0

### ISSUE THREAD

**Issue by marisks** [LucGosso/Gosso.EPiServerAddOn.DownloadIfMissingFileBlob#6]
Error message during update:
'xdt' is an undeclared prefix.

This is related to config transform. I have the configuration already but in a separate file - "EpiserverFramework.config".

**Comment by LucGosso** [comment]
Allright, i'll have to check the transforms, i ll look in to it

**Comment by LucGosso** [comment]
version 2.1.1

**Comment by LucGosso** [comment]
Fixed in version 2.1.1
