### ISSUE TITLE
Provider type could not be loaded.

### ISSUE THREAD

**Issue by Norrj** [LucGosso/Gosso.EPiServerAddOn.DownloadIfMissingFileBlob#7]
I installed the nupgk from release version 2.1.1 into my project with episerver CMS 11.11.2.
The dll were placed into modulebin folder in that project and then I added the provider 

`        <add name="MissingFileBlobProvider"
             Activated="true"
             ProdUrl="http://www.mysite.se/"
             UrlResolverUrl="modules/Gosso.EpiserverAddOn.DownloadIfMissingFileBlob/urlresolver.ashx"
             RestrictedFileExt=".docx.doc.pdf.exe.zip.mov.mp4"
             Cookies="cookie1=cookieValue1;cookie2=cookieValue2"
             type="Gosso.EpiserverAddOn.DownloadIfMissingFileBlob.Provider, Gosso.EpiserverAddOn.DownloadIfMissingFileBlob" />`

I get this error: 
![image](https://user-images.githubusercontent.com/25770971/54275555-3ac0df00-458b-11e9-8302-2d708db3b1f0.png)

Stacktrace:

`
2019-03-13 13:00:21,819 [10] ERROR AVEN-9MT38H2 EPiServer.Framework.Initialization.InitializationEngine: Initialize action failed for 'Initialize on class EPiServer.Framework.FrameworkInitialization, EPiServer.Framework, Version=11.8.1.0, Culture=neutral, PublicKeyToken=8fe83dea738b45b7'
EPiServer.ServiceLocation.ActivationException: Activation error occurred while trying to get instance of type DefaultBlobFactory, key "" ---> StructureMap.Building.StructureMapBuildException: Failure while building 'Lambda: Invoke(value(EPiServer.ServiceLocation.Internal.StructureMapConfiguredType`1+<>c__DisplayClass11_0`1[EPiServer.Framework.Blobs.Internal.DefaultBlobFactory,EPiServer.Framework.Blobs.Internal.DefaultBlobFactory]).instanceAccessor, value(EPiServer.ServiceLocation.Internal.StructureMapConfiguredType`1[EPiServer.Framework.Blobs.Internal.DefaultBlobFactory])._serviceLocator)', check the inner exception for details
1.) Lambda: Invoke(value(EPiServer.ServiceLocation.Internal.StructureMapConfiguredType`1+<>c__DisplayClass11_0`1[EPiServer.Framework.Blobs.Internal.DefaultBlobFactory,EPiServer.Framework.Blobs.Internal.DefaultBlobFactory]).instanceAccessor, value(EPiServer.ServiceLocation.Internal.StructureMapConfiguredType`1[EPiServer.Framework.Blobs.Internal.DefaultBlobFactory])._serviceLocator)
2.) Instance of EPiServer.Framework.Blobs.Internal.DefaultBlobFactory
3.) Container.GetInstance(EPiServer.Framework.Blobs.Internal.DefaultBlobFactory)
 ---> EPiServer.ServiceLocation.ActivationException: Activation error occurred while trying to get instance of type BlobOptions, key "" ---> StructureMap.Building.StructureMapInterceptorException: Decorator Interceptor failed during object construction.  See the inner exception
1.) FuncInterceptor of EPiServer.Framework.Blobs.BlobOptions: Invoke(value(StructureMap.Building.Interception.InterceptorFactory+<>c__DisplayClass2_0`1[EPiServer.Framework.Blobs.BlobOptions]).func, BlobOptions)
2.) EPiServer.Framework.Blobs.BlobOptions
3.) Instance of EPiServer.Framework.Blobs.BlobOptions
4.) Container.GetInstance(EPiServer.Framework.Blobs.BlobOptions)
 ---> System.Configuration.ConfigurationErrorsException: Provider type 'Gosso.EpiserverAddOn.DownloadIfMissingFileBlob.Provider, Gosso.EpiserverAddOn.DownloadIfMissingFileBlob' could not be loaded. (C:\_Avensia\Projects\Nilsongroup\ecommerce\src\Knowit.NilsonGroup.Site\web.config line 573)
   vid EPiServer.Configuration.Transform.Internal.ProviderSettingsValidator.Validate[TProviderContract](ProviderSettings settings, Type& providerType)
   vid EPiServer.Configuration.Transform.Internal.BlobConfigurationTransform.Transform(BlobOptions options, EPiServerFrameworkSection section, IInitializationEngine initializationEngine, IHostingEnvironment hostingEnvironment, IPhysicalPathResolver physicalPathResolver)
   vid EPiServer.Configuration.Transform.Internal.BlobConfigurationTransform.Transform(IServiceLocator serviceLocator, BlobOptions options)
   vid EPiServer.Framework.Initialization.Internal.ConfigurationInitialization.<>c.<ConfigureContainer>b__0_1(IServiceLocator s, BlobOptions o)
   vid EPiServer.ServiceLocation.Internal.StructureMapConfiguration.<>c__DisplayClass19_0`1.<Intercept>b__9(T service)
   vid lambda_method(Closure , IBuildSession , IContext )
   --- Slut på stackspårning för interna undantag ---
   vid lambda_method(Closure , IBuildSession , IContext )
   vid StructureMap.Building.BuildPlan.Build(IBuildSession session, IContext context)
   vid System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   vid StructureMap.SessionCache.GetObject(Type pluginType, Instance instance, ILifecycle lifecycle)
   vid StructureMap.SessionCache.GetDefault(Type pluginType, IPipelineGraph pipelineGraph)
   vid StructureMap.Container.GetInstance(Type pluginType)
   vid EPiServer.ServiceLocation.ServiceLocatorImplBase.GetInstance(Type serviceType, String key)
   --- Slut på stackspårning för interna undantag ---
   vid EPiServer.ServiceLocation.ServiceLocatorImplBase.GetInstance(Type serviceType, String key)
   vid EPiServer.ServiceLocation.ServiceLocatorImplBase.GetInstance[TService]()
   vid EPiServer.Framework.FrameworkInitialization.<>c.<ConfigureContainer>b__0_0(IServiceLocator s)
   vid EPiServer.ServiceLocation.Internal.StructureMapConfiguration.TypedFactory`1.<Create>b__2_0(IServiceLocator s)
   vid lambda_method(Closure , IBuildSession , IContext )
   --- Slut på stackspårning för interna undantag ---
   vid lambda_method(Closure , IBuildSession , IContext )
   vid StructureMap.Building.BuildPlan.Build(IBuildSession session, IContext context)
   vid System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   vid StructureMap.SessionCache.GetObject(Type pluginType, Instance instance, ILifecycle lifecycle)
   vid StructureMap.SessionCache.GetDefault(Type pluginType, IPipelineGraph pipelineGraph)
   vid StructureMap.Container.GetInstance(Type pluginType)
   vid EPiServer.ServiceLocation.ServiceLocatorImplBase.GetInstance(Type serviceType, String key)
   --- Slut på stackspårning för interna undantag ---
   vid EPiServer.ServiceLocation.ServiceLocatorImplBase.GetInstance(Type serviceType, String key)
   vid EPiServer.ServiceLocation.ServiceLocatorImplBase.GetInstance[TService]()
   vid EPiServer.Framework.FrameworkInitialization.InitializeBlobProviders(InitializationEngine context)
   vid EPiServer.Framework.FrameworkInitialization.Initialize(InitializationEngine context)
   vid EPiServer.Framework.Initialization.Internal.ModuleNode.Execute(Action a, String key)
   vid EPiServer.Framework.Initialization.Internal.ModuleNode.Initialize(InitializationEngine context)
   vid EPiServer.Framework.Initialization.InitializationEngine.InitializeModules()
`

**Comment by LucGosso** [comment]
Hej Jesper, Do you have probing in web.config?

  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <probing privatePath="modulesbin" />

PS, you dont need UrlResolverUrl nor Cookies attribute if you don't specific use that features.

**Comment by LucGosso** [comment]
Probing:
`  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <probing privatePath="modulesbin" />`

**Comment by Norrj** [comment]
I do have `<probing privatePath="modulesbin" />` in my web.config and I have removed UrlResolverUrl and Cookies. Still getting the same outcome.

**Comment by LucGosso** [comment]
hmm, try to put the DLL in bin. Just for test. 

Ive never tried with two providers. try to remove the other one "diskBlobProvider" for test. 

Any output?

**Comment by Norrj** [comment]
The diskBlobProvider were removed in my initial test, then I also tried to put the DLL inte he bin folder. I will try it again tomorrow if I messed up somehow. But if you got any other Idea of what it could be ill be really happy for the help.

**Comment by Norrj** [comment]
Think I found the issue, https://github.com/LucGosso/Gosso.EPiServerAddOn.DownloadIfMissingFileBlob/pull/8 .

**Comment by LucGosso** [comment]
Ooh crap, its case sensitive, good you found it.
